# Generated by Django 4.1.4 on 2023-01-04 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("cart_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("description", models.TextField(default="No description.")),
                (
                    "external_product_id",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("isbn", models.CharField(blank=True, max_length=14, null=True)),
                ("upc", models.CharField(blank=True, max_length=14, null=True)),
                ("mpn", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "kickstarter",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "kindle_link",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("preorder_only", models.BooleanField(default=False)),
                ("noorder", models.BooleanField(default=False)),
                ("backorder", models.BooleanField(default=False)),
                ("date_available", models.DateField(blank=True, null=True)),
                ("brand", models.CharField(blank=True, max_length=200, null=True)),
                ("sizes", models.CharField(blank=True, max_length=200, null=True)),
                ("name", models.CharField(max_length=250)),
                ("page", models.CharField(blank=True, max_length=250)),
                ("price", models.IntegerField(default=0)),
                ("image", models.ImageField(blank=True, upload_to="data_here")),
                (
                    "image_name",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                (
                    "tax_code",
                    models.CharField(
                        choices=[
                            ("txcd_99999999", "Goods"),
                            ("txcd_20030000", "Services"),
                            ("txcd_10701100", "Hosting"),
                            ("txcd_34021000", "Phones"),
                            ("txcd_35010000", "Books"),
                            ("txcd_34040014", "Routers"),
                            ("txcd_34020027", "Consumer Electronics"),
                        ],
                        default="txcd_99999999",
                        max_length=20,
                    ),
                ),
                (
                    "cat",
                    models.CharField(
                        choices=[
                            ("B", "Books"),
                            ("S", "Services"),
                            ("E", "Electronics"),
                            ("OE", "Other Electronics"),
                            ("M", "Merch"),
                        ],
                        default="M",
                        max_length=2,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("P", "payment"), ("S", "subscription")],
                        default="P",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField(default=1)),
                ("price_id", models.CharField(max_length=250, null=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.cart"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.product"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(
                related_name="cart_products", to="main.cartproduct"
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
