# Generated by Django 5.2.15 on 2026-07-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_product_isbn_alter_product_upc"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="amazon_link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
