# Generated by Django 5.2.15 on 2026-07-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_product_amazon_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="amazon_in_link",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="bookshop_link",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="flipkart_link",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
