# Generated by Django 5.2.16 on 2026-07-24 22:41

from django.db import migrations, models


def merge_duplicate_cart_products(apps, schema_editor):
    """Collapse pre-existing duplicate (cart, product) rows.

    Adding the constraint fails on any database that already raced its way
    into duplicates, so fold them into the oldest row first: quantities add
    up, M2M links are repointed at the survivor, and the extra rows go.
    """
    CartProduct = apps.get_model("main", "CartProduct")
    Cart = apps.get_model("main", "Cart")
    keepers = {}
    for cart_product in CartProduct.objects.all().order_by("pk"):
        key = (cart_product.cart_id, cart_product.product_id)
        keeper = keepers.get(key)
        if keeper is None:
            keepers[key] = cart_product
            continue
        keeper.quantity += cart_product.quantity
        keeper.save()
        for cart in Cart.objects.filter(products=cart_product):
            cart.products.add(keeper)
        cart_product.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_product_amazon_in_link_product_bookshop_link_and_more"),
    ]

    operations = [
        migrations.RunPython(
            merge_duplicate_cart_products, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="cartproduct",
            constraint=models.UniqueConstraint(
                fields=("cart", "product"), name="unique_cart_product"
            ),
        ),
    ]
