# Generated by Django 5.2.16 on 2026-07-25 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_cartproduct_unique_cart_product"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_session_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending payment"),
                            ("PAID", "Paid"),
                            ("FULFILLED", "Fulfilled"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("customer_name", models.CharField(blank=True, max_length=250)),
                ("shipping_name", models.CharField(blank=True, max_length=250)),
                ("shipping_line1", models.CharField(blank=True, max_length=250)),
                ("shipping_line2", models.CharField(blank=True, max_length=250)),
                ("shipping_city", models.CharField(blank=True, max_length=250)),
                ("shipping_state", models.CharField(blank=True, max_length=250)),
                ("shipping_postal_code", models.CharField(blank=True, max_length=50)),
                ("shipping_country", models.CharField(blank=True, max_length=2)),
                ("billing_name", models.CharField(blank=True, max_length=250)),
                ("billing_line1", models.CharField(blank=True, max_length=250)),
                ("billing_line2", models.CharField(blank=True, max_length=250)),
                ("billing_city", models.CharField(blank=True, max_length=250)),
                ("billing_state", models.CharField(blank=True, max_length=250)),
                ("billing_postal_code", models.CharField(blank=True, max_length=50)),
                ("billing_country", models.CharField(blank=True, max_length=2)),
                ("amount_total", models.IntegerField(default=0)),
                ("amount_subtotal", models.IntegerField(blank=True, null=True)),
                ("amount_tax", models.IntegerField(blank=True, null=True)),
                ("currency", models.CharField(default="usd", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("notification_error", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=250)),
                ("unit_amount", models.IntegerField()),
                ("currency", models.CharField(default="usd", max_length=3)),
                ("quantity", models.PositiveBigIntegerField(default=1)),
                ("price_id", models.CharField(blank=True, max_length=250)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="main.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.product",
                    ),
                ),
            ],
        ),
    ]
