# Generated by Django 5.2.16 on 2026-07-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reconciled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="reconciliation_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="snapshot_quantity",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
