# Generated by Django 5.2.16 on 2026-07-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_order_reconciled_at_order_reconciliation_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
    ]
