# Generated by Django 5.2.16 on 2026-07-26 18:48

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_product_stock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used in signup URLs and in signup forms embedded on other sites. Changing it breaks every form already using the old value; add a new area instead.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Shown next to the option on the signup form.",
                        max_length=300,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive areas stop appearing on signup forms and stop accepting new signups. Existing subscribers are kept.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MailingListMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                (
                    "body",
                    models.TextField(
                        help_text="Plain text. {{ name }}, {{ email }} and {{ unsubscribe_url }} are substituted per recipient; an unsubscribe link is appended if you leave it out."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("D", "draft"), ("G", "sending"), ("S", "sent")],
                        default="D",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mailing_list_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interests",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Which groups to send to. Leave empty to send to every confirmed subscriber.",
                        related_name="messages",
                        to="main.interestarea",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MailingListSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "pending confirmation"),
                            ("S", "subscribed"),
                            ("U", "unsubscribed"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=200)),
                (
                    "token",
                    models.CharField(
                        default=main.models.generate_subscription_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="main.interestarea",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MailingListDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("S", "sent"), ("F", "failed"), ("K", "skipped")],
                        default="S",
                        max_length=1,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="main.mailinglistmessage",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="main.mailinglistsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="mailinglistsubscription",
            index=models.Index(fields=["email"], name="main_mailin_email_a59fa0_idx"),
        ),
        migrations.AddConstraint(
            model_name="mailinglistsubscription",
            constraint=models.UniqueConstraint(
                fields=("email", "interest"), name="unique_subscription_per_interest"
            ),
        ),
        migrations.AddConstraint(
            model_name="mailinglistdelivery",
            constraint=models.UniqueConstraint(
                fields=("message", "subscription"), name="unique_delivery_per_message"
            ),
        ),
    ]
