# Generated by Django 5.2.16 on 2026-07-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_default_interest_area"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interestarea",
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.AddField(
            model_name="interestarea",
            name="catch_all",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Subscribers here get every mailing, whichever groups it is addressed to.",
            ),
        ),
        migrations.AddField(
            model_name="interestarea",
            name="sort_order",
            field=models.PositiveSmallIntegerField(
                db_default=100,
                default=100,
                help_text="Lower sorts earlier on the signup form. Ties break by name.",
            ),
        ),
    ]
