# Generated by Django 5.2.16 on 2026-07-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_product_format_identifiers"),
    ]

    operations = [
        # Nullable on purpose: during a rolling deploy, pods still running the
        # previous release INSERT product rows without this column, and a NOT
        # NULL column with no default would fail those writes. See the
        # OLD_CODE_PRODUCT_COLUMNS guards in test_schema.py / test_stock.py.
        migrations.AddField(
            model_name="product",
            name="bookshop_ebook_link",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
