# Generated by Django 5.2.16 on 2026-07-26 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_product_bookshop_ebook_link"),
        ("newsletter", "0014_article_image_below_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingListMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                (
                    "body",
                    models.TextField(
                        help_text="Plain text. {{ name }}, {{ email }} and {{ unsubscribe_url }} are substituted per recipient; an unsubscribe link is appended if you leave it out."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("D", "draft"), ("G", "sending"), ("S", "sent")],
                        default="D",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("send_started_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mailing_list_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interests",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Which lists to send to. Leave empty to send to every confirmed subscriber of every list.",
                        related_name="mailings",
                        to="newsletter.newsletter",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MailingListDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[("S", "sent"), ("F", "failed")],
                        default="S",
                        max_length=1,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailing_deliveries",
                        to="newsletter.subscription",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="main.mailinglistmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "email"), name="unique_delivery_per_address"
                    ),
                    models.UniqueConstraint(
                        fields=("message", "subscription"),
                        name="unique_delivery_per_message",
                    ),
                ],
            },
        ),
    ]
