# Generated by Django 5.2.16 on 2026-07-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_seed_interest_areas"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailinglistdelivery",
            name="email",
            field=models.EmailField(default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mailinglistmessage",
            name="send_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mailinglistdelivery",
            name="status",
            field=models.CharField(
                choices=[("S", "sent"), ("F", "failed")], default="S", max_length=1
            ),
        ),
        migrations.AddConstraint(
            model_name="mailinglistdelivery",
            constraint=models.UniqueConstraint(
                fields=("message", "email"), name="unique_delivery_per_address"
            ),
        ),
    ]
