# Generated by Django 5.2.16 on 2026-07-28 02:50
#
# Four additions to Product in one migration, on purpose. They are unrelated
# features, but three separate branches would each have generated an 0013 and
# whichever merged first would have forced the other two to renumber and go
# back through review.
#
# Rolling-deploy safety, which is the thing to check if you edit this: `migrate`
# runs on web-primary while pods on the previous image are still writing, so
# every column added here has to be omittable from an INSERT. `msrp` is NULL-
# able; `out_of_date` carries a db_default so the default survives in the
# schema rather than being backfilled and dropped. Neither is listed in the
# OLD_CODE_PRODUCT_COLUMNS fixtures in test_schema/test_stock, which is what
# makes those tests issue an old-code INSERT that omits them. See
# RollingDeployCrossLinkColumnTest.
#
# The two ManyToManyFields add through tables rather than columns on
# main_product, so old code cannot fail to write them -- it never writes them
# at all. Seeding them needs a post-save pass; see seed_products.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_product_bookshop_ebook_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ebook_x_links",
            field=models.ManyToManyField(
                blank=True, related_name="print_x_links", to="main.product"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="msrp",
            field=models.IntegerField(
                blank=True,
                help_text="Suggested retail price in cents, same units as price. Leave empty when there is no MSRP; it is shown struck through beside the price only when it is strictly greater than the price.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="out_of_date",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="x_links",
            field=models.ManyToManyField(blank=True, to="main.product"),
        ),
    ]
