# Generated by Django 5.2.16 on 2026-07-25 19:23

from django.db import migrations, models


def copy_isbn_to_print_isbn(apps, schema_editor):
    Product = apps.get_model("main", "Product")
    Product.objects.filter(print_isbn__isnull=True).update(
        print_isbn=models.F("isbn"))


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_liberatedbread_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="default_asin",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Print/catalogue ASIN fallback for Amazon print links; "
                    "not used for Kindle."
                ),
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ebook_asin",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="ebook_isbn",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="print_asin",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="print_isbn",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(copy_isbn_to_print_isbn, migrations.RunPython.noop),
    ]
