# Generated by Django 5.2.16 on 2026-07-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_product_format_identifiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="digital_delivery_error",
            field=models.TextField(blank=True, db_default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="digital_delivery_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("PHYSICAL", "Physical"),
                    ("DIGITAL", "Digital"),
                    ("SERVICE", "Service"),
                ],
                db_default="PHYSICAL",
                default="PHYSICAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="digital_asset_name",
            field=models.CharField(blank=True, db_default="", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="is_pwyw",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="on_oreilly_safari",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="sells_ebook",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="tax_code",
            field=models.CharField(
                choices=[
                    ("txcd_99999999", "Goods"),
                    ("txcd_20030000", "Services"),
                    ("txcd_10701100", "Hosting"),
                    ("txcd_34021000", "Phones"),
                    ("txcd_35010000", "Books"),
                    ("txcd_10302000", "Digital Books (downloaded)"),
                    ("txcd_34040014", "Routers"),
                    ("txcd_34020027", "Consumer Electronics"),
                ],
                default="txcd_99999999",
                max_length=20,
            ),
        ),
    ]
