# Generated by Django 5.2.16 on 2026-07-26 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_suppressedaddress"),
        ("newsletter", "0014_article_image_below_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglistdelivery",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mailing_deliveries",
                to="newsletter.subscription",
            ),
        ),
    ]
