# Generated by Django 5.2.16 on 2026-07-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_mailinglistdelivery_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="fulfilment_claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
