# Generated by Django 5.2.16 on 2026-07-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_backfill_book_stock"),
        ("main", "0017_emailidentity"),
        ("main", "0017_merge_cross_links_and_mailing_list"),
        ("main", "0017_order_fulfilment_claimed_at"),
    ]

    operations = []
