# Generated by Django 5.2.16 on 2026-07-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    """What the buyer chose to pay for a pay-what-you-want line, in cents.

    Nullable with no backfill on purpose. Null means "no amount named", which
    is every existing row and every ordinary product, and CartProduct.
    effective_unit_amount() reads that as the owner's suggested price -- so
    carts that exist across the deploy keep costing exactly what they did.

    The Stripe Prices those older pay-what-you-want rows carry were minted
    with custom_unit_amount and would now be rejected at checkout; they are
    re-minted per line by CartProduct.refresh_pwyw_price(), rather than here,
    because minting a Price is a network call to Stripe and a migration is
    the wrong place to make one per row.
    """

    dependencies = [
        ("main", "0018_merge_0017_leaves"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartproduct",
            name="chosen_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
