# Generated by Django 5.2.16 on 2026-07-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    """The merge hold, moved from the session onto the cart line it describes.

    "This line's amount was replaced by a merge and the buyer has not seen the
    new one" is a fact about the row, and it has to outlive everything the row
    outlives. Held in the session it did not: logout() flushes the session,
    login() rotates its key, and both leave the repriced cart behind intact.
    Three rounds of review each found a different route to separating the two.

    Defaults to false with no backfill, which is correct for every existing
    row: nothing has been repriced by a merge, so nothing is held.
    """

    dependencies = [
        ("main", "0019_cartproduct_chosen_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartproduct",
            name="pwyw_amount_merged",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
