# Generated by Django 5.2.16 on 2026-07-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_cartproduct_pwyw_amount_merged"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="receipt_error",
            field=models.TextField(blank=True, db_default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="receipt_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
