# Generated by Django 5.2.16 on 2026-07-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_order_receipt_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="release_date",
            field=models.DateField(
                blank=True,
                help_text=(
                    "The date this product was first published/released. "
                    "NULLable so an old pod's INSERT that omits it lands "
                    "NULL safely during a rolling deploy. "
                    "DISTINCT from date_available (when it can be bought): "
                    "this is when it actually came out."
                ),
                null=True,
            ),
        ),
    ]
