# Generated by Django 5.2.16 on 2026-07-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_order_receipt_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publication_year",
            field=models.IntegerField(
                blank=True,
                help_text="The year this product was first published. An integer rather than a date because most rows are books where only the year is reliably known; inventing a month and day would be misleading precision. NULLable so an old pod's INSERT that omits it lands NULL safely during a rolling deploy.",
                null=True,
            ),
        ),
    ]
