# Generated by Django 5.2.16 on 2026-07-30 07:50
#
# A new table, so a rolling deploy needs nothing special from it: an old pod
# has never heard of this model and writes nothing here, and the new pod's
# only writer is the checkout success page's feedback form.
#
# Numbered 0023 rather than 0022: PR #75's release_date migration took that
# number on main while this branch was open. Renumbering rather than adding a
# merge migration keeps the graph linear, and is safe precisely because this
# one has never been applied anywhere -- it has only ever existed on this
# branch.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_release_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                ("may_quote", models.BooleanField(default=False)),
                ("quote_name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="main.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
