# Generated by Django 5.2.17 on 2026-08-18 01:20
#
# Product format groups: one work, several SKUs. See main.models.ProductGroup.
#
# Rolling-deploy safety, the standing requirement for every column added to
# main_product (deploy.yaml migrates on web-primary while pods on the previous
# image keep writing rows, so the new schema is written by code that has never
# heard of the new columns):
#
#   group_id     NULLable -- an omitted column lands NULL, which is also what
#                "this product stands alone" means, so an old-code INSERT
#                produces a correct row and not merely a legal one.
#   format_label NOT NULL, db_default "" -- the default stays in the schema
#                rather than being backfilled and dropped again.
#   format_order NOT NULL, db_default 0 -- likewise.
#
# main_productgroup is a new table, so no old-code write can touch it at all.
# Pinned by ProductFormatGroupSchemaTest in main/tests/test_product_groups.py.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_fix_default_site_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The work's title, shown on the single card that stands for the whole group in listings. Not a format name -- those live on each member's format_label.",
                        max_length=250,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="format_label",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text='How this format is named on the chooser: "Paperback", "E-book". Only meaningful when the product is in a group; falls back to the product name.',
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="format_order",
            field=models.IntegerField(
                db_default=0,
                default=0,
                help_text="Order within the group, lowest first. The lowest-ordered member is the one a collapsed listing shows.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. Other formats of the same work; grouped products share one card in listings and offer each other as format choices.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="main.productgroup",
            ),
        ),
    ]
