# Generated by Django 5.2.17 on 2026-08-25 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_product_format_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="data_here")),
                (
                    "image_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path under static assets/images/, e.g. book_covers/high_performance_spark_2ed.jpg. Preferred over an upload: uploads do not survive a pod restart.",
                        max_length=250,
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Describes the picture for screen readers.",
                        max_length=250,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_default=0,
                        default=0,
                        help_text="Lowest first. Ties break on id, so order is never random.",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_images",
                        to="main.product",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "pk"],
            },
        ),
    ]
